[package]
name = "recurse"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
risc0-zkvm = { version = "1.0.5", features = ["prove"] }
bincode = "1.3.3"
anyhow = "1.0.86"
tracing = "0.1.40"
